Let $s$ be a random variable with discrete probability distribution dependent on $\theta$. Let $z$ be a Gaussian random variable with means and variances dependent on $\theta$ and $s$. Say we have an objective function $L_{\theta}(z)$. We want to compute the gradient of $L$ w.r.t $\theta$. We would like to use Monte-Carlo, but note that the straight forward sampling of $(s,z)$ depend on $\theta$. To compute the gradient using sampling, we will use three different methods: elemntary, Gumbel-softmax, log trick, and the compare them

In [33]:
import numpy as np
from matplotlib import pyplot as plt
from scipy import stats
import tensorflow as tf

dim = 10
buckets = 5
log_P = tf.Variable(np.random.normal(0,1, (1,buckets)))
A = tf.Variable(np.random.normal(0, 1, (dim + buckets,1)), 'A')
B = tf.Variable(np.random.normal(0, 1, 1), 'B')
C = tf.Variable(np.random.normal(0, 1, (dim + buckets,1)), 'C')
D = tf.Variable(np.random.normal(0, 1, 1), 'D')
X = tf.Variable(np.random.normal(0, 1, (1, dim)), 'X')

def get_mu_log_sigma(ss):
    ss_oh = tf.keras.backend.one_hot(ss, buckets)
    X_s = tf.concat([tf.broadcast_to(X, (len(ss), len(X))),ss_oh], axix=0)
    mu = tf.sigmoid(tf.matmul(X,A) + B)
    log_sigma = tf.matmul(X,C) + D
    return mu, log_sigma
    
L=100
seed=1

def elem_loss():
    P = tf.keras.activations.softmax(log_P)
    ss = np.arange(buckets)
    mu, log_sigma = get_mu_log_sigma(ss)
    sigma = tf.exp(log_sigma)
    zs = np.random.normal(0,1,(len(P), 1)) * sigma + mu
    return tf.matmul(P, zs**4)

def gumbel_loss():
    




In [1]:
def loss(z):
    pass
def P_s(theta, s):
    pass
def P_z(s, z):
    pass
def s_sample_space():
    pass

In [ ]:
def elem_grad(loss, theta):
    ss = s_sample_space()
    

In [27]:
tf.keras.backend.one_hot([1,9], 11)

<tf.Tensor: id=120, shape=(2, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>

In [20]:
tf.concat([[[2]],[[3]]], axis=0)

<tf.Tensor: id=63, shape=(2, 1), dtype=int32, numpy=
array([[2],
       [3]], dtype=int32)>

In [26]:
tf.keras.activations.softmax(tf.Variable(np.random.normal(0,1,(1,buckets))))

<tf.Tensor: id=115, shape=(1, 5), dtype=float64, numpy=array([[0.19495575, 0.03686507, 0.25628205, 0.25064562, 0.26125152]])>

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])